In [1]:
import numpy as np
import pandas as pd
import sklearn as sk

# Задание 1.3.1

In [2]:
# Создаем пустую матрицу 8x8, заполненную нулями
matrix = np.zeros((8, 8), dtype=int)

# Заполним чётные клетки (начиная с [0,0]) единицами
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# Задание 1.3.2

In [3]:
row_values = np.arange(5)

# Повторим одномерный массив 5 раз, чтобы создать 5 строк
matrix = np.tile(row_values, (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# Задание 1.3.3

In [4]:
# Создаем массив 3x3x3 со случайными значениями от 0 до 1
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.09763841 0.95718281 0.64971458]
  [0.84034869 0.31822408 0.86078446]
  [0.4387154  0.58758281 0.01888897]]

 [[0.30068274 0.4844596  0.57937175]
  [0.18433471 0.07045953 0.9329755 ]
  [0.47526839 0.28272974 0.11726481]]

 [[0.15065536 0.71039246 0.6981671 ]
  [0.91617588 0.90661152 0.49758726]
  [0.55154812 0.74780334 0.68147916]]]


# Задание 1.3.4

In [5]:
import numpy as np

# Создаем матрицу 5x5, заполненную нулями
matrix = np.zeros((5, 5), dtype=int)

# Устанавливаем значения на границах равными 1
matrix[0, :] = 1  # Верхняя граница
matrix[-1, :] = 1  # Нижняя граница
matrix[:, 0] = 1  # Левая граница
matrix[:, -1] = 1  # Правая граница

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Задание 1.3.5

In [7]:
# Создаем массив
my_array = np.array([3, 4, 8, 2, 5])

# Сортируем массив по убыванию
sorted_array = np.sort(my_array)[::-1]

# Выводим отсортированный массив
print(sorted_array)

[8 5 4 3 2]


# Задание 1.3.6

In [8]:
# Создадим матрицу 3x4 (3 строки, 4 столбца) с произвольными значениями
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Выведем форму матрицы
print("Форма матрицы:", matrix.shape)

# Выведем размер матрицы
print("Размер матрицы:", matrix.size)

# Выведем размерность матрицы
print("Размерность матрицы:", matrix.ndim)

Форма матрицы: (3, 4)
Размер матрицы: 12
Размерность матрицы: 2


# Задание 2.3.1

In [9]:
# Создадим два NumPy массива, представляющих точки a и b
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

# Вычислим квадрат разности между a и b для каждой координаты
squared_diff = (a - b) ** 2

# Вычислим сумму квадратов разностей
sum_squared_diff = squared_diff.sum()

# Вычислим квадратный корень из суммы квадратов разностей
euclidean_distance = np.sqrt(sum_squared_diff)

print("Евклидово расстояние между a и b:", euclidean_distance)

Евклидово расстояние между a и b: 5.196152422706632


# Задание 2.3.2

In [10]:
# Замените URL ниже на URL CSV-файла, который вы хотите загрузить
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"

# Загрузите CSV-файл во фрейм данных
df = pd.read_csv(url)

# Выведите первые несколько строк фрейма данных для проверки
print(df.head(5))

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa


# Задание 2.3.3

In [11]:
df.head(2)
df.tail(3)
df.shape
df.describe()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
count       150.000000      150.000000       150.000000      150.000000
mean          5.843333        3.054000         3.758667        1.198667
std           0.828066        0.433594         1.764420        0.763161
min           4.300000        2.000000         1.000000        0.100000
25%           5.100000        2.800000         1.600000        0.300000
50%           5.800000        3.000000         4.350000        1.300000
75%           6.400000        3.300000         5.100000        1.800000
max           7.900000        4.400000         6.900000        2.500000

In [12]:
df.loc[1:5]

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa
5              5.4             3.9              1.7             0.4  setosa

In [13]:
# Отбираем строки, где значение в столбце "sepal_length" больше 5.0
filtered_df = df[df['sepal_length_cm'] > 5.0].head(2)

print(filtered_df)

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
5              5.4             3.9              1.7             0.4  setosa


# Задание 3.3.2

In [14]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
 
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
df = pd.read_csv(url)

# Выведем первые несколько строк фрейма данных для проверки
print("Исходный фрейм данных:\n")
print(df.head())

# Создаем объекты для минимаксного преобразования и z-масштабирования
minmax_scaler = MinMaxScaler()
z_scaler = StandardScaler()

# Нормализуем первый числовой признак (sepal_length_cm) с использованием минимаксного преобразования
df['sepal_length_cm'] = minmax_scaler.fit_transform(df[['sepal_length_cm']])

# Нормализуем второй числовой признак (sepal_width_cm) с использованием z-масштабирования
df['sepal_width_cm'] = z_scaler.fit_transform(df[['sepal_width_cm']])

# Выведем обновленный фрейм данных с нормализованными признаками
print("\nФрейм данных после нормализации:\n")
print(df.head())

Исходный фрейм данных:

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

Фрейм данных после нормализации:

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
